TEMPLATES = [
    # Core route expressions
    "bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "buses from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{SOURCE_NAME} to {DESTINATION_NAME} bus",
    "show buses between {SOURCE_NAME} and {DESTINATION_NAME}",
    "find buses from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book ticket from {SOURCE_NAME} to {DESTINATION_NAME}",
    "search trip {SOURCE_NAME} to {DESTINATION_NAME}",

    # Route with city codes
    "bus from {SOURCE_CITY_CODE} to {DESTINATION_CITY_CODE}",
    "{SOURCE_CITY_CODE} to {DESTINATION_CITY_CODE} buses",
    "show buses from {SOURCE_NAME} ({SOURCE_CITY_CODE}) to {DESTINATION_NAME} ({DESTINATION_CITY_CODE})",
    "find route {SOURCE_CITY_CODE} to {DESTINATION_NAME}",
    "book bus from {SOURCE_NAME} to {DESTINATION_CITY_CODE}",
    "search buses from {SOURCE_CITY_CODE} to {DESTINATION_NAME}",

    # Date and departure time
    "bus from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}",
    "buses from {SOURCE_NAME} to {DESTINATION_NAME} at {DEPARTURE_TIME}",
    "bus from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} at {DEPARTURE_TIME}",
    "{DEPARTURE_DATE} {DEPARTURE_TIME} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "show buses from {SOURCE_NAME} to {DESTINATION_NAME} for {DEPARTURE_DATE} in {DEPARTURE_TIME}",
    "need a bus from {SOURCE_NAME} to {DESTINATION_NAME} leaving {DEPARTURE_TIME} {DEPARTURE_DATE}",
    
     # AC + seat + operator combinations with punctuation cues
    "{OPERATOR}, {AC_TYPE}, {SEAT_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{OPERATOR} - {AC_TYPE} - {SEAT_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{OPERATOR} ({AC_TYPE}) {SEAT_TYPE} service from {SOURCE_NAME} to {DESTINATION_NAME}",
    "find {OPERATOR} buses: {AC_TYPE}, {SEAT_TYPE}, route {SOURCE_NAME} to {DESTINATION_NAME}",
    "book {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}, ac {AC_TYPE}, seat {SEAT_TYPE}",

    # Distinguish BUS_TYPE from AC_TYPE clearly
    "{BUS_TYPE} bus by {OPERATOR} with {AC_TYPE} and {SEAT_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "show {BUS_TYPE} operated by {OPERATOR} with ac category {AC_TYPE} and seat category {SEAT_TYPE}",
    "need {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}; operator {OPERATOR}; ac {AC_TYPE}; seat {SEAT_TYPE}",
    "{OPERATOR} {BUS_TYPE} service from {SOURCE_NAME} to {DESTINATION_NAME} with {AC_TYPE} and {SEAT_TYPE}",
    "book {BUS_TYPE} under {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} with {AC_TYPE} {SEAT_TYPE}",

    # Date/time + arrival + pickup/drop with separated style
    "operator {OPERATOR}, ac {AC_TYPE}, seat {SEAT_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} at {DEPARTURE_TIME} arrive {ARRIVAL_TIME}",
    "{OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}, departure {DEPARTURE_TIME}, arrival {ARRIVAL_TIME}, ac {AC_TYPE}, seat {SEAT_TYPE}",
    "book {OPERATOR}; route {SOURCE_NAME} to {DESTINATION_NAME}; pickup {PICKUP_POINT}; drop {DROP_POINT}; ac {AC_TYPE}; seat {SEAT_TYPE}",
    "find buses from {SOURCE_NAME} to {DESTINATION_NAME}: operator {OPERATOR}, pickup {PICKUP_POINT}, drop {DROP_POINT}, ac {AC_TYPE}, seat {SEAT_TYPE}",

    # Coupon/deal/add-on + core transport entities
    "apply {COUPON_CODE} for operator {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} with {AC_TYPE} and {SEAT_TYPE}",
    "show {DEALS} on {OPERATOR} buses from {SOURCE_NAME} to {DESTINATION_NAME}, ac {AC_TYPE}, seat {SEAT_TYPE}",
    "book {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} with coupon {COUPON_CODE}, deal {DEALS}, add-on {ADD_ONS}",
    "need {OPERATOR} {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME} with {COUPON_CODE}, {DEALS}, and {ADD_ONS}",
    "find {OPERATOR} buses with {AC_TYPE}, {SEAT_TYPE}, {COUPON_CODE}, and budget {PRICE}",

    # Semantic + traveler + amenities while preserving boundaries
    "for {TRAVELER}, book operator {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} with {AC_TYPE}, {SEAT_TYPE}, and {AMENITIES}",
    "need {SEMANTIC} option: operator {OPERATOR}, bus {BUS_TYPE}, ac {AC_TYPE}, seat {SEAT_TYPE}, route {SOURCE_NAME} to {DESTINATION_NAME}",
    "show {SEMANTIC} buses for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME} with operator {OPERATOR} and ac {AC_TYPE}",
    "book for {TRAVELER}: {OPERATOR} {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}, seat {SEAT_TYPE}, ac {AC_TYPE}, amenities {AMENITIES}",
    "prefer {SEMANTIC} ride with {OPERATOR}, {AC_TYPE}, {SEAT_TYPE}, pickup {PICKUP_POINT}, drop {DROP_POINT}"
    
    # Arrival constraints
    "bus from {SOURCE_NAME} to {DESTINATION_NAME} arriving {ARRIVAL_TIME}",
    "show buses from {SOURCE_NAME} to {DESTINATION_NAME} that reach {ARRIVAL_TIME}",
    "find trip {SOURCE_NAME} to {DESTINATION_NAME} depart {DEPARTURE_TIME} arrive {ARRIVAL_TIME}",
    "need {SOURCE_NAME} to {DESTINATION_NAME} bus by {ARRIVAL_TIME}",
    "book bus from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} arriving {ARRIVAL_TIME}",

    # Bus, AC, and seat preferences
    "{BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{AC_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{SEAT_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{BUS_TYPE} {SEAT_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{AC_TYPE} {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{AC_TYPE} {SEAT_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{AC_TYPE} {BUS_TYPE} {SEAT_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "show {BUS_TYPE} with {SEAT_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "find {AC_TYPE} buses from {SOURCE_NAME} to {DESTINATION_NAME}",

    # Operator specific
    "{OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{OPERATOR} {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{OPERATOR} {SEAT_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{OPERATOR} {AC_TYPE} {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "show only {OPERATOR} buses from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}",

    # Pickup and drop preferences
    "bus from {SOURCE_NAME} to {DESTINATION_NAME} pickup at {PICKUP_POINT}",
    "bus from {SOURCE_NAME} to {DESTINATION_NAME} drop at {DROP_POINT}",
    "bus from {SOURCE_NAME} to {DESTINATION_NAME} pickup {PICKUP_POINT} drop {DROP_POINT}",
    "{SOURCE_NAME} to {DESTINATION_NAME} boarding {PICKUP_POINT} dropping {DROP_POINT}",
    "show buses from {SOURCE_NAME} to {DESTINATION_NAME} with pickup at {PICKUP_POINT}",
    "find buses from {SOURCE_NAME} to {DESTINATION_NAME} dropping at {DROP_POINT}",
    "book bus from {SOURCE_NAME} to {DESTINATION_NAME} from {PICKUP_POINT} to {DROP_POINT}",

    # Amenities and features
    "bus from {SOURCE_NAME} to {DESTINATION_NAME} with {AMENITIES}",
    "{BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME} with {AMENITIES}",
    "show buses from {SOURCE_NAME} to {DESTINATION_NAME} having {AMENITIES}",
    "find {BUS_FEATURES} buses from {SOURCE_NAME} to {DESTINATION_NAME}",
    "{BUS_FEATURES} {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "need {AMENITIES} and {BUS_FEATURES} for {SOURCE_NAME} to {DESTINATION_NAME}",
    "book {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} with {AMENITIES}",

    # Deals, add-ons, and budget
    "show {DEALS} buses from {SOURCE_NAME} to {DESTINATION_NAME}",
    "find {DEALS} offer for bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book bus from {SOURCE_NAME} to {DESTINATION_NAME} with {ADD_ONS}",
    "show buses from {SOURCE_NAME} to {DESTINATION_NAME} under {PRICE}",
    "need bus from {SOURCE_NAME} to {DESTINATION_NAME} below {PRICE}",
    "find {DEALS} buses from {SOURCE_NAME} to {DESTINATION_NAME} under {PRICE}",
    "book {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} with {ADD_ONS} and budget {PRICE}",

    # Semantic intent
    "show {SEMANTIC} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "find {SEMANTIC} options from {SOURCE_NAME} to {DESTINATION_NAME}",
    "need {SEMANTIC} {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book {SEMANTIC} {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "get {SEMANTIC} buses from {SOURCE_NAME} to {DESTINATION_NAME} under {PRICE}",

    # Traveler-specific
    "book for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "need seats for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "find {SEAT_TYPE} bus for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "show {OPERATOR} buses for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book {TRAVELER} trip from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}",
    "need {TRAVELER} booking from {SOURCE_NAME} to {DESTINATION_NAME} with {ADD_ONS}",

    # Natural conversational variants
    "i need a bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "can you find a bus from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}",
    "please book {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "help me get {SEAT_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "i want to travel from {SOURCE_NAME} to {DESTINATION_NAME} at {DEPARTURE_TIME}",
    "show me {OPERATOR} buses from {SOURCE_NAME} to {DESTINATION_NAME}",
    "i prefer {AC_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book from {SOURCE_NAME} to {DESTINATION_NAME} and include {AMENITIES}",
    "find buses from {SOURCE_NAME} to {DESTINATION_NAME} and apply {DEALS}",

    # Full multi-entity templates for dense supervision
    "{OPERATOR} {AC_TYPE} {BUS_TYPE} {SEAT_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} at {DEPARTURE_TIME}",
    "{OPERATOR} {BUS_TYPE} from {SOURCE_NAME} ({SOURCE_CITY_CODE}) to {DESTINATION_NAME} ({DESTINATION_CITY_CODE}) on {DEPARTURE_DATE}",
    "book {OPERATOR} {AC_TYPE} {BUS_TYPE} {SEAT_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} at {DEPARTURE_TIME} pickup {PICKUP_POINT} drop {DROP_POINT}",
    "find {SEMANTIC} {BUS_FEATURES} {OPERATOR} buses from {SOURCE_NAME} to {DESTINATION_NAME} with {AMENITIES}",
    "show {DEALS} {OPERATOR} {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME} under {PRICE}",
    "need {TRAVELER} tickets in {SEAT_TYPE} for {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} {DEPARTURE_DATE}",
    "{SOURCE_NAME} to {DESTINATION_NAME} {DEPARTURE_DATE} {DEPARTURE_TIME} arrive {ARRIVAL_TIME} {BUS_TYPE} {SEAT_TYPE}",
    "find {AC_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME} with {AMENITIES} and {ADD_ONS}",
    "book {SEMANTIC} bus for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME} with budget {PRICE}",
    "show {BUS_FEATURES} {BUS_TYPE} buses from {SOURCE_CITY_CODE} to {DESTINATION_CITY_CODE} for {DEPARTURE_DATE}",
    "need {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} pickup {PICKUP_POINT} drop {DROP_POINT} with {ADD_ONS}",
    "find {DEALS} and {ADD_ONS} on {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book {TRAVELER} on {OPERATOR} {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME} with {AMENITIES} under {PRICE}",
    "show buses from {SOURCE_NAME} to {DESTINATION_NAME} {DEPARTURE_DATE} {DEPARTURE_TIME} with {BUS_FEATURES} and {SEMANTIC}",

    # Coupon, deals, traveler, pickup, and arrival heavy templates
    "apply {COUPON_CODE} on bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book {TRAVELER} ticket from {SOURCE_NAME} to {DESTINATION_NAME} using {COUPON_CODE}",
    "show {DEALS} and apply coupon {COUPON_CODE} for {SOURCE_NAME} to {DESTINATION_NAME}",
    "need {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} with {COUPON_CODE} and {DEALS}",
    "find buses from {SOURCE_NAME} to {DESTINATION_NAME} pickup {PICKUP_POINT} arrive {ARRIVAL_TIME}",
    "book {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME} pickup at {PICKUP_POINT} arrive by {ARRIVAL_TIME}",
    "show buses for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME} with pickup {PICKUP_POINT} and drop {DROP_POINT}",
    "need {SEAT_TYPE} for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME} arriving {ARRIVAL_TIME}",
    "find {BUS_TYPE} buses for {TRAVELER} pickup {PICKUP_POINT} drop {DROP_POINT}",
    "book {OPERATOR} {BUS_TYPE} for {TRAVELER} with {COUPON_CODE}",
    "show {DEALS} for {TRAVELER} on {OPERATOR} buses",
    "find buses arriving {ARRIVAL_TIME} with pickup at {PICKUP_POINT}",
    "need pickup point {PICKUP_POINT} and arrival {ARRIVAL_TIME} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} for {TRAVELER} with coupon {COUPON_CODE}",
    "show {COUPON_CODE} applicable buses from {SOURCE_NAME} to {DESTINATION_NAME} under {PRICE}",
    "find {DEALS} {ADD_ONS} and {COUPON_CODE} for {SOURCE_NAME} to {DESTINATION_NAME}",
    "need {TRAVELER} booking with {ADD_ONS} and {COUPON_CODE}",
    "book {TRAVELER} on {DEPARTURE_DATE} at {DEPARTURE_TIME} arriving {ARRIVAL_TIME}",
    "show {OPERATOR} buses with {DEALS} for {TRAVELER} arriving {ARRIVAL_TIME}",
    "find {AC_TYPE} {SEAT_TYPE} bus for {TRAVELER} with pickup {PICKUP_POINT}",
    "book {BUS_TYPE} from {SOURCE_CITY_CODE} to {DESTINATION_CITY_CODE} for {TRAVELER} with coupon {COUPON_CODE}",
    "show buses from {SOURCE_CITY_CODE} to {DESTINATION_CITY_CODE} with {DEALS} arriving {ARRIVAL_TIME}",
    "find {OPERATOR} {BUS_FEATURES} bus from {SOURCE_NAME} to {DESTINATION_NAME} coupon {COUPON_CODE}",
    "need {SEMANTIC} bus for {TRAVELER} with {AMENITIES} and {COUPON_CODE}",
    "book {SOURCE_NAME} to {DESTINATION_NAME} pickup {PICKUP_POINT} drop {DROP_POINT} for {TRAVELER} with {DEALS}",
    "show options from {SOURCE_NAME} to {DESTINATION_NAME} for {TRAVELER} under {PRICE} using {COUPON_CODE}",
    "apply {COUPON_CODE} and find {DEALS} for {OPERATOR} {BUS_TYPE}",
    "need {TRAVELER} seats with {SEAT_TYPE} arriving {ARRIVAL_TIME} and pickup {PICKUP_POINT}",
    "find buses with {ADD_ONS} and {DEALS} for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} for {TRAVELER} with {COUPON_CODE} and {ADD_ONS}",
    "show {BUS_FEATURES} buses for {TRAVELER} pickup {PICKUP_POINT} drop {DROP_POINT} arrive {ARRIVAL_TIME}",
    "find {SEMANTIC} route {SOURCE_NAME} to {DESTINATION_NAME} for {TRAVELER} with coupon {COUPON_CODE}",
    "need {DEALS} bus with {AMENITIES} for {TRAVELER} on {DEPARTURE_DATE}",
    "book {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME} with {DEALS} {COUPON_CODE} and budget {PRICE}",
    "show {OPERATOR} buses pickup {PICKUP_POINT} arrive {ARRIVAL_TIME} with coupon {COUPON_CODE}",
    "find buses for {TRAVELER} with {COUPON_CODE} from {SOURCE_NAME} to {DESTINATION_NAME} at {DEPARTURE_TIME}",
    "need {TRAVELER} booking from {SOURCE_NAME} to {DESTINATION_NAME} arriving {ARRIVAL_TIME} with {ADD_ONS}",
    "book {TRAVELER} with {COUPON_CODE} and {DEALS} pickup {PICKUP_POINT} drop {DROP_POINT}",
    "show {SEMANTIC} buses with {COUPON_CODE} and {DEALS} for {SOURCE_NAME} to {DESTINATION_NAME}",
    "find {OPERATOR} {AC_TYPE} {BUS_TYPE} for {TRAVELER} using {COUPON_CODE} arriving {ARRIVAL_TIME}",
    "book {OPERATOR} {AC_TYPE} {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} at {DEPARTURE_TIME} pickup {PICKUP_POINT} drop {DROP_POINT}",
    "show {DEALS} {OPERATOR} {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME} under {PRICE}",
    "need {TRAVELER} tickets in {SEAT_TYPE} for {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} {DEPARTURE_DATE}",
    "{SOURCE_NAME} to {DESTINATION_NAME} {DEPARTURE_DATE} {DEPARTURE_TIME} arrive {ARRIVAL_TIME} {BUS_TYPE} {SEAT_TYPE}",
    "find {AC_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME} with {AMENITIES} and {ADD_ONS}",
    "book {SEMANTIC} bus for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME} with budget {PRICE}",
    "show {BUS_FEATURES} {BUS_TYPE} buses from {SOURCE_CITY_CODE} to {DESTINATION_CITY_CODE} for {DEPARTURE_DATE}",
    "need {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} pickup {PICKUP_POINT} drop {DROP_POINT} with {ADD_ONS}",
    "find {DEALS} and {ADD_ONS} on {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book {TRAVELER} on {OPERATOR} {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME} with {AMENITIES} under {PRICE}",
    "show buses from {SOURCE_NAME} to {DESTINATION_NAME} {DEPARTURE_DATE} {DEPARTURE_TIME} with {BUS_FEATURES} and {SEMANTIC}",
    "apply {COUPON_CODE} on bus from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book {TRAVELER} ticket from {SOURCE_NAME} to {DESTINATION_NAME} using {COUPON_CODE}",
    "show {DEALS} and apply coupon {COUPON_CODE} for {SOURCE_NAME} to {DESTINATION_NAME}",
    "need {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} with {COUPON_CODE} and {DEALS}",
    "find buses from {SOURCE_NAME} to {DESTINATION_NAME} pickup {PICKUP_POINT} arrive {ARRIVAL_TIME}",
    "book {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME} pickup at {PICKUP_POINT} arrive by {ARRIVAL_TIME}",
    "show buses for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME} with pickup {PICKUP_POINT} and drop {DROP_POINT}",
    "need {SEAT_TYPE} for {TRAVELER} from {SOURCE_NAME} to {DESTINATION_NAME} arriving {ARRIVAL_TIME}",
    "find {BUS_TYPE} buses for {TRAVELER} pickup {PICKUP_POINT} drop {DROP_POINT}",
    "book {OPERATOR} {BUS_TYPE} for {TRAVELER} with {COUPON_CODE}",
    "show {DEALS} for {TRAVELER} on {OPERATOR} buses",
    "find buses arriving {ARRIVAL_TIME} with pickup at {PICKUP_POINT}",
    "need pickup point {PICKUP_POINT} and arrival {ARRIVAL_TIME} from {SOURCE_NAME} to {DESTINATION_NAME}",
    "book from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} for {TRAVELER} with coupon {COUPON_CODE}",
    "show {COUPON_CODE} applicable buses from {SOURCE_NAME} to {DESTINATION_NAME} under {PRICE}",
    "find {DEALS} {ADD_ONS} and {COUPON_CODE} for {SOURCE_NAME} to {DESTINATION_NAME}",
    "need {TRAVELER} booking with {ADD_ONS} and {COUPON_CODE}",
    "book {TRAVELER} on {DEPARTURE_DATE} at {DEPARTURE_TIME} arriving {ARRIVAL_TIME}",
    "show {OPERATOR} buses with {DEALS} for {TRAVELER} arriving {ARRIVAL_TIME}",
    "find {AC_TYPE} {SEAT_TYPE} bus for {TRAVELER} with pickup {PICKUP_POINT}",
    "book {BUS_TYPE} from {SOURCE_CITY_CODE} to {DESTINATION_CITY_CODE} for {TRAVELER} with coupon {COUPON_CODE}",
    "show buses from {SOURCE_CITY_CODE} to {DESTINATION_CITY_CODE} with {DEALS} arriving {ARRIVAL_TIME}",
    "find {OPERATOR} {BUS_FEATURES} bus from {SOURCE_NAME} to {DESTINATION_NAME} coupon {COUPON_CODE}",
    "need {SEMANTIC} bus for {TRAVELER} with {AMENITIES} and {COUPON_CODE}",
    "book {SOURCE_NAME} to {DESTINATION_NAME} pickup {PICKUP_POINT} drop {DROP_POINT} for {TRAVELER} with {DEALS}",
    "show options from {SOURCE_NAME} to {DESTINATION_NAME} for {TRAVELER} under {PRICE} using {COUPON_CODE}",
    "apply {COUPON_CODE} and find {DEALS} for {OPERATOR} {BUS_TYPE}",
    "need {TRAVELER} seats with {SEAT_TYPE} arriving {ARRIVAL_TIME} and pickup {PICKUP_POINT}",
    "find {BUS_TYPE} buses for {TRAVELER} pickup {PICKUP_POINT} drop {DROP_POINT}",
    "book {OPERATOR} {BUS_TYPE} for {TRAVELER} with {COUPON_CODE}",
    "show {DEALS} for {TRAVELER} on {OPERATOR} buses",
    "find buses arriving {ARRIVAL_TIME} with pickup at {PICKUP_POINT}",
    "need pickup point {PICKUP_POINT} and arrival {ARRIVAL_TIME} from {SOURCE_NAME} to {DESTINATION_NAME}",


#    RAw DATA
     "i would like to explore bus travel options from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"{OPERATOR} bus services from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"i am unable to book tickets for the bus from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}.",
"what discounts and coupons are available for my {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i am looking for buses from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what is the {ADD_ONS} amount if I choose {ADD_ONS} for my {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"open promo codes for bus {COUPON_CODE}.",
"I am unable to use my gift card for {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"I'm looking for any available {BUS_TYPE} bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"I would like to know about available discounts or {ADD_ONS} for my booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}.",
"What is the {ADD_ONS} for my booking from {SOURCE_NAME} to {DESTINATION_NAME}?",
"Why has the booking process for {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} not been completed?",
"{AC_TYPE} bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"direct buses from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"{OPERATOR} bus services.",
"what discounts and coupons are available for my journey on {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what is the {ADD_ONS} for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to book a ticket from {SOURCE_NAME} to {DESTINATION_NAME} for the departure date of {DEPARTURE_DATE}.",
"please provide the {COUPON_CODE} for the {PRICE} {ADD_ONS}.",
"is there a {ADD_ONS} fee for the {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what is the {ADD_ONS} for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to know about the {ADD_ONS} for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what is the {ADD_ONS} for the bus?",
"show me bus options for traveling from {SOURCE_NAME} to {DESTINATION_NAME}",
"show me private bus options from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}, specifically focusing on {BUS_FEATURES} bus options and excluding all government buses.",
"i would like to know the bus schedule from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"i need a bus ticket for {DEPARTURE_TIME} from {SOURCE_NAME} to {DESTINATION_NAME}.",
"why are the discounts not being applied for my journey with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"is there a {ADD_ONS} fee for the bus booking from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}?",
"what {AMENITIES} are available on the {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"is the final {PRICE} of {PRICE} for the bus from {SOURCE_NAME} to {DESTINATION_NAME} based on the distance, or will the distance be calculated after the booking?",
"show me both {AC_TYPE} and {AC_TYPE} bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what happens to my refund if my next journey from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} is already confirmed?",
"what {DEALS} and {COUPON_CODE} are available for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"please provide information about bus options from {PICKUP_POINT}, {SOURCE_NAME} to {DESTINATION_NAME} for {DEPARTURE_DATE} at {DEPARTURE_TIME}.",
"is there a {ADD_ONS} fee for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"show me bus options from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"i want to know about buses from {SOURCE_NAME}.",
"what is the {ADD_ONS} policy for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to book bus tickets from {SOURCE_NAME} to {DESTINATION_NAME}.",
"show me all {BUS_TYPE} bus options from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}, including departure times, duration, fare, and rating.",
"will i get food with my ticket from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to know about group booking options for traveling from {SOURCE_NAME} to {DESTINATION_NAME} for {PRICE} travelers.",
"i need to travel from {SOURCE_NAME} to {DESTINATION_NAME}, departing on {DEPARTURE_DATE} and returning to {SOURCE_NAME} on {DEPARTURE_DATE}.",
"is there a {ADD_ONS} fee for cancelling my bus ticket with {OPERATOR}?",
"i want to book a bus ticket from {SOURCE_NAME} to {DESTINATION_NAME}. please provide me with the available buses on this route.",
"what is {ADD_ONS} for my journey from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to book tickets for my journey from {SOURCE_NAME} to {DESTINATION_NAME} {DEPARTURE_DATE}.",
"what is the {ADD_ONS} for the journey with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"show me the bus stops of {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i am looking for details about my bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what are the penalty charges for {ADD_ONS} with {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i would like to know how to apply the available coupons during my booking for the {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what is the {ADD_ONS} policy for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what are the penalty charges for cancelling my booking on the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what is the last departure time for buses from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}? i am planning to take a bus with {OPERATOR} at {DEPARTURE_TIME}.",
"i want to book an {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}, departing at {DEPARTURE_TIME} on {DEPARTURE_DATE}.",
"what is the cost for {ADD_ONS} with {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"show me buses from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"what discounts and coupons are available for my bus journey from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}?",
"i am looking for buses from {SOURCE_NAME} to {DESTINATION_NAME}",
"is there a {ADD_ONS} fee for my {OPERATOR} booking from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what is the {ADD_ONS} for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what {DEALS} and {COUPON_CODE} are available for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"show me the best coupons available for the {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i am unable to use my gift card balance for bus bookings.",
"what is {ADD_ONS} for bus services? please provide detailed information about this service.",
"show me bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what discounts and coupons are available for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"is there a bus stop after {DROP_POINT}?",
"i want to book a {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME} for {DEPARTURE_DATE}.",
"is there a {ADD_ONS} fee for my bus booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"is there a {ADD_ONS} fee for my bus ticket from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}?",
"what are the traveller details for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what discounts and coupons are available for my bus journey from {SOURCE_NAME} to {DESTINATION_NAME} on {OPERATOR}?",
"i want to book a bus from {SOURCE_NAME} to {DESTINATION_NAME} via {SOURCE_NAME} on {DEPARTURE_DATE}",
"i need to find bus options for traveling from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i want to know about the {ADD_ONS} for the {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}.",
"when will i receive the driver details for the journey with {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i don't have any specific reasons for not booking my ticket from {SOURCE_NAME} to {DESTINATION_NAME}. can you help me finalize my bus ticket?",
"i would like to know more about the bus amenities or policies for the bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"show me {BUS_TYPE} bus options to reach {DROP_POINT} from {SOURCE_NAME}.",
"i want to travel from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}. can you help me?",
"i want to book a bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what discounts and coupons are available for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"please show me bus options in {SOURCE_NAME}.",
"i want to book a round trip bus from {SOURCE_NAME} to {DESTINATION_NAME} with a departure date of {DEPARTURE_DATE}.",
"please provide information about {OPERATOR} bus services, including routes, schedules, and ticket prices.",
"is the bus from {SOURCE_NAME} to {DESTINATION_NAME} {AC_TYPE}?",
"i need an offer for my bus journey from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}.",
"what is the {ADD_ONS} amount if I choose {ADD_ONS} for my {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"is the drop point in {DROP_POINT} the same as the bus stop for '{OPERATOR}'?",
"what should we do for 5 people traveling in {SEAT_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}, considering one of us is older?",
"please arrange travel from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i need to find the {SEMANTIC} bus options for traveling from {SOURCE_NAME} to {DESTINATION_NAME}.",
"is there a {ADD_ONS} fee for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to book a bus from {SOURCE_NAME} to {DESTINATION_NAME} for {DEPARTURE_DATE} looking for the {SEMANTIC} option under {PRICE}.",
"i want to book a bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"please book the tickets for {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"i want to book a bus from {PICKUP_POINT} to {DESTINATION_NAME} after my flight lands at {DEPARTURE_TIME} on {DEPARTURE_DATE}.",
"mujhe {SOURCE_NAME} se {DESTINATION_NAME} ki bus ke operation ya master ka contact number chahiye.",
"please check for bus options from {SOURCE_NAME} to {DESTINATION_NAME} for {DEPARTURE_DATE}.",
"what is the {PRICE} for a bus trip from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}?",
"reserve a women's seat on the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"will there be a bus change during the journey from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}?",
"is there a {ADD_ONS} fee for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"use {SOURCE_NAME} as the source for the bus service to {DESTINATION_NAME}.",
"what discounts and coupons are available for my bus journey from {SOURCE_NAME} to {DESTINATION_NAME} on '{OPERATOR}'?",
"i want to know about the specific amenities available on the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"show me the bus drop points for {OPERATOR} services from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i am looking for travel options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i would like information on the {ADD_ONS} and refund eligibility for {OPERATOR} bus tickets from {SOURCE_NAME} to {DESTINATION_NAME}.",
"please find the bus ticket prices for traveling from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what {DEALS} and {COUPON_CODE} are available for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what is the rating of the {OPERATOR} bus?",
"what will be the ticket {PRICE} for buses from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}?",
"what is the {ADD_ONS} policy for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i am looking for morning buses from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"i need to find bus options from {SOURCE_NAME} to {DESTINATION_NAME} departing at {DEPARTURE_TIME}.",
"what are the penalty charges for {ADD_ONS} with {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i would like to proceed with the bus booking from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i need to find bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i want to travel from {SOURCE_NAME} to {DESTINATION_NAME} on the morning of {DEPARTURE_DATE}.",
"i want to know about the {OPERATOR} bus.",
"why did the ticket price increase when i was paying for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"provide details on available amenities such as {AMENITIES} and {AMENITIES} for the {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i want to book a return ticket for the journey with {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"show me the available buses from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"i want a ticket from {SOURCE_NAME} to {DESTINATION_NAME}.",
"list down {SEAT_TYPE} bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i need a ticket for {DESTINATION_NAME} on the {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}, but the prices seem high for the shortest distance.",
"show me buses from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"what discounts and coupons are available for my bus journey from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}?",
"i want to travel from {SOURCE_NAME} to {DESTINATION_NAME}. please suggest some bus options.",
"i need help planning my trip to {DESTINATION_NAME} from {SOURCE_NAME}.",
"show me bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"which buses from {SOURCE_NAME} to {DESTINATION_NAME} offer {ADD_ONS}?",
"i need to find a bus from {PICKUP_POINT} to {DESTINATION_NAME}.",
"which bus station should i select to reach the nearest bus station for traveling from {SOURCE_NAME} to {DROP_POINT}?",
"what are the penalty charges for cancelling the bus ticket from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} with {OPERATOR}?",
"i wish to find the {SEMANTIC} bus options from {SOURCE_NAME} to {DESTINATION_NAME} for my trip on {DEPARTURE_DATE} during the daytime.",
"what discounts and coupons are available for my bus journey from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}?",
"is there a {ADD_ONS} fee for my bus booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to book a bus ticket from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what are the bus timings from {SOURCE_NAME} to {DESTINATION_NAME} around {DEPARTURE_TIME}?",
"why is my trip plan not showing for the journey from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}?",
"show me bus options for traveling from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what is the {ADD_ONS} policy for my bus booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"is there a {ADD_ONS} fee for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what is the cost for {ADD_ONS} for the {BUS_TYPE} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i have a {COUPON_CODE} for my {OPERATOR} bus booking from {SOURCE_NAME} to {DESTINATION_NAME}, but it's not working. can you help me resolve this issue?",
"what are the available intercity express bus services from {SOURCE_NAME} to {DESTINATION_NAME}, including timings and pricing?",
"i want to book a bus from {SOURCE_NAME} to {DESTINATION_NAME} using {OPERATOR}. please show me the available bus options with timings, fares, and seat availability so i can choose one.",
"what discounts and coupons are available for {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"why am i unable to use the coupon code for my travel from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to travel by bus from {SOURCE_NAME} to {DESTINATION_NAME}, and i need to stop nearby {DESTINATION_NAME} since there is no direct stop available.",
"why are my tickets not booked for {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i would like to add {DESTINATION_NAME} to my journey starting from {SOURCE_NAME} at {DEPARTURE_TIME} in the morning.",
"is there a bus stand on {DROP_POINT} where the bus stops?",
"what discounts and coupons are available for {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what is the {ADD_ONS} policy for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i am looking for buses from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} between {DEPARTURE_TIME} and {DEPARTURE_TIME} under {PRICE}.",
"show me {DEPARTURE_TIME} buses from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"please find me bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"is there a {ADD_ONS} fee for my bus booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"my booking for {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"what {DEALS} and {COUPON_CODE} are available for the {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"please assist me with my booking {ADD_ONS} and refund status, as my refund has not been credited yet.",
"what is the {ADD_ONS} policy for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what are the penalty charges for {ADD_ONS} with {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"is there a {ADD_ONS} fee for my bus booking from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}?",
"what is the coupon code for bus bookings?",
"is an alternative trip plan mandatory for confirming a ticket from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i need to find a bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i want to travel to {DESTINATION_NAME}, but not on {DEPARTURE_DATE}.",
"i need 5 tickets from {SOURCE_NAME} to {DESTINATION_NAME}.",
"please find more bus options for the route from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what is the alternative trip option available for my journey from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}?",
"yes, i would like to know the specific route or stops along the way for the bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i want to know about {OPERATOR} bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i need a bus ticket for a child from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}.",
"is there a {ADD_ONS} fee for my bus booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what is the {ADD_ONS} for the {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"{SEMANTIC} bus transportation options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what is the refund amount I will receive if I choose {ADD_ONS} for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"why am I unable to apply the {COUPON_CODE} for my booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}, considering I have never booked a trip before?",
"what is {ADD_ONS} for bus travel from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what is the {ADD_ONS} policy for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what are the {ADD_ONS} charges for my bus booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to book a bus with {ADD_ONS}.",
"i want to see bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"please assist in modifying the {OPERATOR} bus itinerary to shift from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what is the route of the {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what discounts and coupons are available for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to book a bus ticket to {DESTINATION_NAME} from {SOURCE_NAME}.",
"what is the {ADD_ONS} for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what discounts and coupons are available for my bus journey from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}?",
"why are there no applicable coupons or discounts for this bus?",
"show me {AC_TYPE} bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what discounts and coupons are available for my bus journey from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}?",
"show me the {SEMANTIC} bus journey from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"no cancel her ticket how much is the {ADD_ONS}.",
"show me the best {COUPON_CODE} available for {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}",
"what is the {ADD_ONS} policy for the journey with {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to book a {SEAT_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME} for the {DEPARTURE_TIME} of {DEPARTURE_DATE}.",
"i would like to know more about the refund process and any other policies related to {OPERATOR}.",
"i am looking for {OPERATOR} buses from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what is the {ADD_ONS} policy for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"show me bus options for traveling from {SOURCE_NAME} to {DESTINATION_NAME}.",
"please arrange a call for me to book a ticket from {SOURCE_NAME} to {DESTINATION_NAME}.",
"the mmt app is not showing {BUS_TYPE} run by {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i want to know about the offers available for my journey from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"what are the chances of getting the {BUS_FEATURES} feature?",
"what is the {ADD_ONS} for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what discounts and coupons are available for my bus journey from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}?",
"is there a {ADD_ONS} fee for my bus booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"is there a {ADD_ONS} fee for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"show me bus options for traveling from {SOURCE_NAME} to {DESTINATION_NAME}",
"please confirm my ticket from {SOURCE_NAME} to {DESTINATION_NAME} for {DEPARTURE_DATE}",
"tell me more about the {ADD_ONS} trip {ADD_ONS} coverage options for bus bookings.",
"what discounts and coupons are available for my journey on '{OPERATOR}' from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what is the best {COUPON_CODE} bus coupon code?",
"i need to book a bus from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"i need to book a bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"is there a {ADD_ONS} fee for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to see bus options from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"is there a {ADD_ONS} fee for {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"please proceed with the {ADD_ONS} of my bus ticket that I booked.",
"show me direct bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i want to book a ticket for a ladies traveler on the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i need a {OPERATOR} bus for my journey from {SOURCE_NAME} to {DESTINATION_NAME}.",
"please proceed with booking 5 tickets on the {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME} and include a {DEALS}.",
"is there a {ADD_ONS} fee for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what is the route for the {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"{AC_TYPE} {SEAT_TYPE} buses from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}",
"I would like to know more about the {ADD_ONS} and other {ADD_ONS} for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"proceed with booking the bus from {SOURCE_NAME} to {DESTINATION_NAME} for {PRICE}, which takes {ARRIVAL_TIME}.",
"what discounts and coupons are available for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i would like to use my credit card coupon for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME} during the payment process.",
"show me available buses from {SOURCE_NAME} to {DESTINATION_NAME}.",
"show me bus options from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i am looking for information about {OPERATOR}, including its services, routes, and booking options.",
"i need to change my boarding point to a different one for my {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"please provide details on how to cancel a ticket.",
"i want to travel from {SOURCE_NAME} to {DESTINATION_NAME} by bus.",
"my coupon code for the {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME} isn't working. can you help me resolve this issue?",
"i want to choose a bus from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} in the {DEPARTURE_TIME}.",
"what are the penalty charges for {ADD_ONS} with {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what discounts and coupons are available for {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"show me buses from {SOURCE_NAME} to {DESTINATION_NAME}.",
"{OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"please check the {ADD_ONS} details for my booking. it is showing a {ADD_ONS} while booking the ticket, but when i am going to do the payment, it is not showing the {ADD_ONS}. why is that?",
"{OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"is there a {COUPON_CODE} available for my {COUPON_CODE} booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to book an {AC_TYPE} bus ticket from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what are the penalty charges for cancelling the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"yes, i would like to know about the specific {DEALS} available for my journey with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what is the cost for {ADD_ONS} for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want 5 tickets from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}, and 5 tickets from {DESTINATION_NAME} to {DESTINATION_NAME} on the {DEPARTURE_DATE} night.",
"show me the booking options for the bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i need assistance with booking a {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"is there a {ADD_ONS} fee for the '{BUS_TYPE}' from {SOURCE_NAME} to {DESTINATION_NAME}?",
"is there a {ADD_ONS} fee for my bus booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to know about the {ADD_ONS} for the bus operated by {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what is the coupon code for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"is there a {ADD_ONS} fee for my {OPERATOR} bus ticket from {SOURCE_NAME} to {DESTINATION_NAME}?",
"show me buses from {SOURCE_NAME} to {DESTINATION_NAME} for {DEPARTURE_DATE}.",
"what is the pick-up location for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to know about {OPERATOR} bus services.",
"i am unable to book the ticket for the {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"please add bus travel to my existing bookings.",
"i want to find bus options for traveling from {SOURCE_NAME} to {DESTINATION_NAME}.",
"show me buses from {SOURCE_NAME} to {DESTINATION_NAME}.",
"please confirm my ticket from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"which area does the dropping point in {DROP_POINT} belong to for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i need to book a bus from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE} with a drop time {ARRIVAL_TIME}, for a {SEAT_TYPE} at the {PRICE}.",
"what is the {ADD_ONS} policy for the {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"show me available buses from {SOURCE_NAME} to {DESTINATION_NAME} for {DEPARTURE_DATE}.",
"is there any bus route from {SOURCE_NAME} to a destination near {DESTINATION_NAME}?",
"please call me regarding my booking status from {SOURCE_NAME} to {DESTINATION_NAME}.",
"track the bus route from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i need to share the bus journey options from {SOURCE_NAME} to {DESTINATION_NAME} with my friend.",
"i want to know about {ADD_ONS} for my trip from {SOURCE_NAME} to {DESTINATION_NAME}.",
"what is the contact number for the bus {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"will the windows open on the {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to book my child's ticket also, but my child is {PRICE} years old. is it considered a full or half ticket for the journey from {SOURCE_NAME} to {DESTINATION_NAME}?",
"please allow permission regarding my bus booking with {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}.",
"track the live location of the bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"please provide the current bus rates in {SOURCE_NAME} for {DEPARTURE_DATE}.",
"we want to avoid paying {ADD_ONS} for travel from {SOURCE_NAME} to {DESTINATION_NAME}. please provide options for {ADD_ONS} or any other alternatives that would help us avoid these charges.",
"what {DEALS} and {COUPON_CODE} are available for my bus journey from {SOURCE_NAME} to {DESTINATION_NAME} with {OPERATOR}?",
"what is the process to opt for {ADD_ONS} for my journey from {SOURCE_NAME} to {DESTINATION_NAME}?",
"i want to travel from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i want to find bus options for traveling from {SOURCE_NAME} to {DESTINATION_NAME}.",
"{OPERATOR} bus from {PICKUP_POINT}",
"please connect me with customer support regarding my refund query for the bus that was cancelled by the {OPERATOR}.",
"i want to travel from {SOURCE_NAME} to {DESTINATION_NAME} on {DEPARTURE_DATE}.",
"i want to track the live location of a bus",
"what discounts and coupons are available for the bus service {OPERATOR} from {SOURCE_NAME} to {DESTINATION_NAME}?",
"what happens if my {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME} is cancelled by the operator?",
"what are the reviews for {ADD_ONS}?",
"is there a food stop on the {BUS_TYPE} bus from {SOURCE_NAME} to {DESTINATION_NAME}?",
"no, i do not want to proceed with {OPERATOR} bus from {SOURCE_NAME} to {DESTINATION_NAME}.",
"i want to know the bus route from {SOURCE_NAME} to {DESTINATION_NAME}.",
]
